server:
  port: 8010

app:
  instance:
    name: Concurrency01

#### 【以下Mongo連線配置】 ####
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/db_dev_flash_sale_mongo

####此為開發環境的Redis配置檔####
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
