####【應用種類(服務集群名稱)】####
app:
  type: high-concurrency-processor

####【MQ配置】####
spring.cloud:
  stream:
    bindings: # 配置消息通道的通用設置，不特定於任何消息中間件。
      highConcurrencyProcessor_BusinessExchangeProducerChannel-out-0: # 宣告通道名稱(若無在此指定binder，則使用myMQ.properties裡面的預設binder)
        content-type: application/json
        destination: businessExchange # 此通道使用哪個交換機

    rabbit:
      bindings: # 配置 RabbitMQ 特有的消息通道設置
        highConcurrencyProcessor_BusinessExchangeProducerChannel-out-0:
          producer:
            # 必須在這個層級設定routing-key，在spring.cloud.stream.bindings中設定沒用(因為不是每個中間件都有routingKey的概念)。routing-key-expression指定固定字串的話，前後需加三引號。
            routing-key-expression: headers['routingKey']